In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("data/yoga_ds_with_keypoints.csv")
df.head()

,pose,filename,format,width,height,nose_x,nose_y,nose_score,left_eye_x,left_eye_y,...,left_knee_score,right_knee_x,right_knee_y,right_knee_score,left_ankle_x,left_ankle_y,left_ankle_score,right_ankle_x,right_ankle_y,right_ankle_score
0,hanumanasana,3-0.png,PNG,440,299,0.261698,0.512255,0.630277,0.237344,0.517355,...,0.720410,0.722782,0.674401,0.858969,0.683820,0.050615,0.601454,0.795440,0.924660,0.741907
1,hanumanasana,21-0.png,PNG,466,453,0.394864,0.491497,0.831882,0.370693,0.487102,...,0.849817,0.805349,0.174530,0.807741,0.908731,0.943022,0.840723,0.702517,0.003883,0.777568
2,hanumanasana,45-0.png,PNG,397,228,0.430713,0.753430,0.800470,0.439265,0.780632,...,0.298566,0.719260,0.579058,0.182867,0.728648,0.731057,0.359210,0.723543,0.732710,0.500341
3,hanumanasana,67-0.png,PNG,493,402,0.369197,0.440116,0.678368,0.368485,0.460600,...,0.868513,0.786196,0.241361,0.973960,0.854160,0.963011,0.850752,0.808341,0.036816,0.808559
4,hanumanasana,25-0.png,PNG,518,336,0.262922,0.548760,0.764848,0.245587,0.531681,...,0.888956,0.755988,0.298930,0.832813,0.741362,0.910159,0.891368,0.699116,0.092350,0.673872

In [5]:
# yx coordinates are normalized to image frame, i.e. range in [0.0, 1.0] of the 17 keypoints
df.describe()

,width,height,nose_x,nose_y,nose_score,left_eye_x,left_eye_y,left_eye_score,right_eye_x,right_eye_y,...,left_knee_score,right_knee_x,right_knee_y,right_knee_score,left_ankle_x,left_ankle_y,left_ankle_score,right_ankle_x,right_ankle_y,right_ankle_score
count,5994.000000,5994.000000,5994.000000,5994.000000,5994.000000,5994.000000,5994.000000,5994.000000,5994.000000,5994.000000,...,5994.000000,5994.000000,5994.000000,5994.000000,5994.000000,5994.000000,5994.000000,5994.000000,5994.000000,5994.000000
mean,429.707708,361.710878,0.402485,0.505240,0.643202,0.392777,0.512010,0.674613,0.392655,0.498716,...,0.663980,0.589134,0.445047,0.663129,0.653548,0.525076,0.600185,0.651593,0.455671,0.606329
std,237.293535,204.589043,0.208851,0.265225,0.168151,0.217474,0.270520,0.164364,0.217472,0.270923,...,0.227487,0.177698,0.213840,0.222796,0.234839,0.288437,0.241100,0.237473,0.284904,0.245327
min,16.000000,26.000000,0.002803,-0.020719,0.001595,-0.004444,-0.031503,0.001253,-0.003339,-0.034443,...,0.006132,0.009578,-0.004629,0.011100,0.006360,-0.031651,0.010184,-0.000919,-0.008318,0.007832
25%,269.000000,233.250000,0.230323,0.301329,0.548488,0.208477,0.296696,0.577340,0.209563,0.289223,...,0.549450,0.477022,0.278480,0.551040,0.525209,0.260892,0.437969,0.523452,0.180152,0.437129
50%,393.000000,324.000000,0.385639,0.503402,0.670592,0.378394,0.521606,0.694554,0.375001,0.485381,...,0.730317,0.578853,0.436512,0.723846,0.687720,0.520145,0.663995,0.687822,0.450132,0.673332
75%,553.000000,446.000000,0.550888,0.714601,0.772368,0.547665,0.728661,0.799372,0.547105,0.718744,...,0.837188,0.721370,0.602988,0.834838,0.855353,0.810689,0.790801,0.855219,0.697230,0.803486
max,3949.000000,4262.000000,0.990988,1.010201,0.926177,0.989277,1.008240,0.963243,0.993018,1.005647,...,0.981310,1.008242,0.990679,0.976571,1.011292,0.998377,0.972109,1.000914,0.991899,0.970609

In [9]:
df_Xy = df.loc[:, df.columns.str.endswith(("_x", "_y", "pose"))]
df_Xy.head()

,pose,nose_x,nose_y,left_eye_x,left_eye_y,right_eye_x,right_eye_y,left_ear_x,left_ear_y,right_ear_x,...,right_hip_x,right_hip_y,left_knee_x,left_knee_y,right_knee_x,right_knee_y,left_ankle_x,left_ankle_y,right_ankle_x,right_ankle_y
0,hanumanasana,0.261698,0.512255,0.237344,0.517355,0.238441,0.486026,0.242483,0.497878,0.248089,...,0.651845,0.414223,0.678855,0.221365,0.722782,0.674401,0.683820,0.050615,0.795440,0.924660
1,hanumanasana,0.394864,0.491497,0.370693,0.487102,0.375714,0.461120,0.381811,0.450995,0.400140,...,0.807697,0.396388,0.854739,0.710447,0.805349,0.174530,0.908731,0.943022,0.702517,0.003883
2,hanumanasana,0.430713,0.753430,0.439265,0.780632,0.419011,0.763575,0.482887,0.787360,0.431683,...,0.622483,0.486750,0.743239,0.589924,0.719260,0.579058,0.728648,0.731057,0.723543,0.732710
3,hanumanasana,0.369197,0.440116,0.368485,0.460600,0.366005,0.458955,0.407975,0.471238,0.402241,...,0.778978,0.435595,0.848863,0.726469,0.786196,0.241361,0.854160,0.963011,0.808341,0.036816
4,hanumanasana,0.262922,0.548760,0.245587,0.531681,0.244322,0.532350,0.257699,0.483209,0.258080,...,0.624212,0.459428,0.690590,0.708224,0.755988,0.298930,0.741362,0.910159,0.699116,0.092350

In [10]:
df_Xy.to_csv("data/yoga_ds_Xy.csv", index=False)